### ISSUE TITLE
Use mock content in local development environment

### ISSUE THREAD

**Issue by edisonz0718** [storyprotocol/project-nova#135]
**Problem**
Currently our content is preloaded from S3 and store in the memory for faster serving. However, our open-source contributors don't have access to S3.

To address this, we can provide some mock content in file system and preload mock content when the environment is 'local'.

**Comment by edisonz0718** [comment]
We already have a fs implementation for story content in the repository/story_content.go 
So a simple update is to update the main.go file to use `repository.NewStoryContentFsImpl(cfg.ContentPath)` instead of `repository.NewStoryContentS3Impl(s3Client, cfg.S3ContentBucketName)` when the environment is local

**Comment by edisonz0718** [comment]
And for mock data, you can create a folder structure under api/resource like below
api/
 resource/
   content/
      project-nova/
         1:1:1/
            content.json
         1:1:2/
            content.json

I will send you the content.json file. Don't check in these files.

**Comment by brentju** [comment]
I followed the instructions on the page about mocking the DB and I was wondering if there was some way I needed to check if the user was doing local development and have some control flow logic there and alternate between mock and S3 workflows, or if it would just be okay to comment out the existing code to connect to AWS for now and only have the local mock files to work with?

**Comment by edisonz0718** [comment]
Yes! There are existing pkg for you to check the environment. The package code is in /pkg/config/env.go. 
So to check if it's local environment, in main.go you can do something like: 
```
if xconfig.GetEnv() == xconfig.Environments.Local {
    <init fs implementation>
} else {
    <init S3 implementation>
}
```

xconfig refers to the config package in the pkg folder

**Comment by brentju** [comment]
It appears there's already a config package under api/internal/config that is giving me a redeclaration error, could you advise me on how I should proceed from here?
