### ISSUE TITLE
Add /v1/ as the prefix to all APIs

### ISSUE THREAD

**Issue by LeoHChen** [storyprotocol/project-nova#38]
use /v1/ as the prefix to all api, so that we can leave it for upgrade later for /v2.

normally when an API published to public, we shouldn't change it. so to use /v1 to make it more flexible if we need to release /v2 api.

**Comment by edisonz0718** [comment]
Done. All APIs are made public with doc and example calls in Postman. https://documenter.getpostman.com/view/25015244/2s935ivSkW
