### ISSUE TITLE
Build a CI Workflow 

### ISSUE THREAD

**Issue by AndyBoWu** [storyprotocol/project-nova#7]
CONTEXT

I had a meeting with @edisonz0718  on Friday discussing some CI work we can automate. Also, we discussed the possibility to use Argocd for CD work. 

DONE WHEN
1/ build a GHA workflow to lint/build/push images (2 in total)
2/ finalize the decision about image tagging

**Comment by edisonz0718** [comment]
@AndyBoWu Is this done so that we can close?
